### ISSUE TITLE
TypeError('Path must be a string.....

### ISSUE THREAD

**Issue by cadecairos** [mozilla/thimble.mozilla.org#1486]
I was notified of this error in the logs:

```
» 18 May 2016 13:02:49.212 67 <190>1 2016-05-18T17:02:49.100414+00:00 host app web.1 - path.js:8
» 18 May 2016 13:02:49.325 118 <190>1 2016-05-18T17:02:49.100428+00:00 host app web.1 - throw new TypeError('Path must be a string. Received ' +
» 18 May 2016 13:02:49.325 63 <190>1 2016-05-18T17:02:49.100454+00:00 host app web.1 - ^
» 18 May 2016 13:02:49.325 58 <190>1 2016-05-18T17:02:49.100455+00:00 host app web.1 -
» 18 May 2016 13:02:49.325 110 <190>1 2016-05-18T17:02:49.100456+00:00 host app web.1 - TypeError: Path must be a string. Received undefined
» 18 May 2016 13:02:49.325 90 <190>1 2016-05-18T17:02:49.100457+00:00 host app web.1 - at assertPath (path.js:8:11)
» 18 May 2016 13:02:49.325 98 <190>1 2016-05-18T17:02:49.100457+00:00 host app web.1 - at Object.posix.join (path.js:479:5)
» 18 May 2016 13:02:49.325 133 <190>1 2016-05-18T17:02:49.100458+00:00 host app web.1 - at Request._callback (/app/server/routes/auth/oauth2-callback.js:87:30)
» 18 May 2016 13:02:49.325 130 <190>1 2016-05-18T17:02:49.100459+00:00 host app web.1 - at Request.self.callback (/app/node_modules/request/index.js:148:22)
» 18 May 2016 13:02:49.325 90 <190>1 2016-05-18T17:02:49.100460+00:00 host app web.1 - at emitTwo (events.js:87:13)
» 18 May 2016 13:02:49.325 95 <190>1 2016-05-18T17:02:49.100461+00:00 host app web.1 - at Request.emit (events.js:172:7)
» 18 May 2016 13:02:49.325 128 <190>1 2016-05-18T17:02:49.100461+00:00 host app web.1 - at Request.<anonymous> (/app/node_modules/request/index.js:876:14)
» 18 May 2016 13:02:49.325 90 <190>1 2016-05-18T17:02:49.100462+00:00 host app web.1 - at emitOne (events.js:82:20)
» 18 May 2016 13:02:49.325 95 <190>1 2016-05-18T17:02:49.100462+00:00 host app web.1 - at Request.emit (events.js:169:7)
```

It looks related to the OAuth callback endpoint

**Comment by gideonthomas** [comment]
This seems to be a weird state issue (the locale is not set in the session just before being redirected to id on clicking "Login" OR more likely that the session is destroyed/stale). Someone logging out and then clicking "Back" or something like that. We should probably not throw when this happens though.

**Comment by humphd** [comment]
I can't even find this code anymore, closing.
