### ISSUE TITLE
One specific project not loading for user

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1590]
Project is ``https://thimble.mozilla.org/en-US/user/egmun/619155``

According to the user, only this project won't load for them, while others do. Has tried different browser and is not in Private mode.

@gideonthomas Can you check into the DB to see if there is anything special about this project?

Received via email from Gustav.

**Comment by flukeout** [comment]
@gideonthomas here's the pasted log, is it indicative of any kind of known issue?

```
bramble.js:3 MessagePort cannot send an ArrayBuffer as a transferable object yet. See http://crbug.com/334408i @ bramble.js:3
main.js:10 MessagePort cannot send an ArrayBuffer as a transferable object yet. See http://crbug.com/334408i @ main.js:10
main.js:8 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (https://mozillathimblelivepreview.net/bramble/production/dist/main.js:39:21544)
    at n (https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/thirdparty.min.js:4:17337)
    at Object.<anonymous> (https://mozillathimblelivepreview.net/bramble/production/dist/extensions/default/brackets-paste-and-indent/main.js:1:567)
    at Object.execCb (https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:11617)
    at Z.check (https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:6012)
    at Z.enable (https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:8516)
    at Z.init (https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:5175)
    at E (https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:3769)
    at Object.completeLoad (https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:10922)i @ main.js:8
main.js:8 Registering for deprecated event 'currentDocumentChange'. Instead, use MainViewManager.currentFileChange. Error
    at Object.u [as on] (https://mozillathimblelivepreview.net/bramble/production/dist/main.js:8:14781)
    at Object.<anonymous> (https://mozillathimblelivepreview.net/bramble/production/dist/extensions/default/brackets-paste-and-indent/main.js:1:585)
    at Object.execCb (https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:11617)
    at Z.check (https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:6012)
    at Z.enable (https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:8516)
    at Z.init (https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:5175)
    at E (https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:3769)
    at Object.completeLoad (https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:10922)
    at HTMLScriptElement.onScriptLoad (https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:11742)u @ main.js:8
```

**Comment by gideonthomas** [comment]
There's something special about this project that is preventing it from being loaded (I'm not able to load it either) so I'm gonna try to debug this today and will post my findings (and a recovery solution) soon.

**Comment by flukeout** [comment]
We were able to extract this project from the DB and email a zip archive for the user. The problem seemed to lie in a non-english character (like ä) in either the project title or description. 

Will file separate issue to investigate non-english chars.
