### ISSUE TITLE
Error Template doesn't render 

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2053]
While debugging #2049, and bringing down the id and login servers, that Thimble's error templates don't seem to always render.  See also #1797.

> Template render error: (/vagrant/views/error.html)
  Error: template not found: remix-projects.html
    at Object.exports.prettifyError (/vagrant/node_modules/nunjucks/src/lib.js:34:15)
    at /vagrant/node_modules/nunjucks/src/environment.js:486:31
    at eval (eval at <anonymous> (/vagrant/node_modules/nunjucks/src/environment.js:565:24), <anonymous>:52:11)
    at createTemplate (/vagrant/node_modules/nunjucks/src/environment.js:212:25)
    at next (/vagrant/node_modules/nunjucks/src/lib.js:210:13)
    at handle (/vagrant/node_modules/nunjucks/src/environment.js:252:25)
    at /vagrant/node_modules/nunjucks/src/environment.js:263:21
    at next (/vagrant/node_modules/nunjucks/src/lib.js:207:13)
    at Object.exports.asyncIter (/vagrant/node_modules/nunjucks/src/lib.js:214:5)
    at Obj.extend.getTemplate (/vagrant/node_modules/nunjucks/src/environment.js:242:17)

It's weird that this fails to find the `remix-projects.html` template [here](https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/views/error.html#L63) since we do have it [here](https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/views/remix-projects.html).  I wonder if it's missing data it needs in one of the places we [render it](https://github.com/mozilla/thimble.mozilla.org/search?utf8=%E2%9C%93&q=render%28+error.html&type=)

**Comment by humphd** [comment]
The problem here is *maybe* that we only send the status code on our [data object](https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/server/lib/http-error.js#L48).

**Comment by humphd** [comment]
To reproduce this:

* Load Thimble at `http://localhost:3500`
* Login on the Homepage
* In your terminal, type `vagrant ssh` and then `pm2 stop login && pm2 stop id`
* Try to open your Projects List

You can restart those 2 services with `pm2 start login && pm2 start id`
