### ISSUE TITLE
Allow user to change the project description without needing to publish their project.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2479]
Currently in the publish dialog, there is a Description field. However, it only saves what you put in there at the moment of publishing, which isn't ideal. Sometimes people don't want to publish a project, but want to leave a description.

I think we should just auto-save whatever is in the description when a user closes the Publish dialog.

**Comment by jmrodriguesgoncalves** [comment]
Hello, I am a Seneca student working on a project for my Open Source course. I am looking around for ways in which to help out, and this looks like something I want to try working on. This would be my first bug so I am pretty new. Guidance would be much appreciated!

**Comment by humphd** [comment]
@flukeout, @gideonthomas can you give some technical insights here on what you want @jmrodriguesgoncalves to do in order to begin?  Thanks.

**Comment by gideonthomas** [comment]
It's all yours @jmrodriguesgoncalves.  I would suggest starting by setting up Thimble on your machine for development. You can find instructions on how to do that in the [README](https://github.com/mozilla/thimble.mozilla.org/blob/master/README.md). 

Once you have Thimble setup, make sure you are able to reproduce the issue mentioned above - projects descriptions are not saved until you publish a project. 

To fix this issue, I believe you need to add a function to `Publisher.prototype` (like https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/ui/publisher.js#L47) that calls the `Metadata.update` function from the `project/metadata` module. A similar call can be found here: https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/ui/publisher.js#L47. Then, in the `init` function of the `Publisher` module, setup an event listener on `this.dialogEl` and call the function you created below.

I think that should fix your issue, but let us know if you have any issues and we'd be happy to help out.

**Comment by jmrodriguesgoncalves** [comment]
@gideonthomas many thanks, I'm pretty sure you just about answered all of the questions I had in my mind. I will report back if I run into any issues!

**Comment by Avedis777** [comment]
I'm a student at Seneca college learning open source, and I was hoping to work on this bug for my course.  If no one else is currently working on it, I'd like to give it a try.

**Comment by jmrodriguesgoncalves** [comment]
hey, @Avedis777 currently working on this one. Keep your notifications opened in case I run into some trouble but for now I got it. You can feel free to come and have a look at the code when we are in class!

**Comment by jmrodriguesgoncalves** [comment]
Hello again, I am able to reproduce the bug mentioned here on the released version of Thimble and I have already had a look at the code. As such I wanted to setup a testing environment. I went through the instructions provided in the README file @gideonthomas provided, however after days on end of trying I can't seem to figure out why I am not able to run this command. Having already installed everything that is needed prior, when I run "npm run env" this is what I see:

![q](https://user-images.githubusercontent.com/14240261/31207744-198a4f04-a94e-11e7-8d14-6af4ae4a2ec1.JPG)

A quick look at the log shows me this:

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'env' ]
2 info using npm@5.3.0
3 info using node@v8.6.0
4 verbose run-script [ 'preenv', 'env', 'postenv' ]
5 info lifecycle thimble.mozilla.org@2.0.0~preenv: thimble.mozilla.org@2.0.0
6 info lifecycle thimble.mozilla.org@2.0.0~env: thimble.mozilla.org@2.0.0
7 verbose lifecycle thimble.mozilla.org@2.0.0~env: unsafe-perm in lifecycle true
8 verbose lifecycle thimble.mozilla.org@2.0.0~env: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Joao\desktop\SchoolWork\Year5\Semester1\DPS909\patch\thimble.mozilla.org\node_modules\.bin;C:\Users\Joao\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Joao\bin;C:\Program Files\Git\cmd;C:\app\Joao\product\11.2.0\client_1\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Rational\common;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Android\Android Studio\gradle\gradle-2.4\bin;C:\Android\sdk\tools;C:\Android\sdk\platform-tools;C:\Android\sdk;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\Skype\Phone;C:\Program Files\Git\cmd;C:\HashiCorp\Vagrant\bin;C:\Program Files\nodejs;C:\Users\Joao\.cargo\bin;C:\Program Files\Java\jdk1.8.0_25\bin;C:\Users\Joao\AppData\Local\Microsoft\WindowsApps;C:\Users\Joao\AppData\Local\GitHubDesktop\bin;C:\Users\Joao\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle thimble.mozilla.org@2.0.0~env: CWD: C:\Users\Joao\desktop\SchoolWork\Year5\Semester1\DPS909\patch\thimble.mozilla.org
10 silly lifecycle thimble.mozilla.org@2.0.0~env: Args: [ '/d /s /c', 'shx cp env.dist .env' ]
11 silly lifecycle thimble.mozilla.org@2.0.0~env: Returned: code: 1  signal: null
12 info lifecycle thimble.mozilla.org@2.0.0~env: Failed to exec env script
13 verbose stack Error: thimble.mozilla.org@2.0.0 env: `shx cp env.dist .env`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid thimble.mozilla.org@2.0.0
15 verbose cwd C:\Users\Joao\desktop\SchoolWork\Year5\Semester1\DPS909\patch\thimble.mozilla.org
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "env"
18 verbose node v8.6.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error thimble.mozilla.org@2.0.0 env: `shx cp env.dist .env`
22 error Exit status 1
23 error Failed at the thimble.mozilla.org@2.0.0 env script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Any help on this would be very much appreciated!

**Comment by humphd** [comment]
I think the relevant bit is:

```
Failed to exec env script
13 verbose stack Error: thimble.mozilla.org@2.0.0 env: shx cp env.dist .env
13 verbose stack Exit status 1
```

What I think is happening here is that the docs are asking you to run the `env` stuff *before* `npm install` is called, which fails because it depends on a file be installed for this to run.  Another student in the class hit this too--we should be fixing the docs cc @gideonthomas.

Try running:

```
npm install
```

Then do what you did above again.  If that fixes it, let's get the docs updated ASAP!

**Comment by jmrodriguesgoncalves** [comment]
So I have to say thanks first @humphd there seems to have been some progress, however things still don't seem to be quite ready yet. I did what you said, all whilst having Brackets running in the background. After attempting to start Thimble, once all the install and env stuff is finished, this is what I see (Thimble is on the left, Brackets is on the right):

![q2](https://user-images.githubusercontent.com/14240261/31232069-b618dd82-a9b6-11e7-80df-5b6f3f819478.JPG)

I think this have something to do with Brackets this time around, but I am not quite sure. I will keep trying to figure this out until hearing back from you!

**Comment by humphd** [comment]
@jmrodriguesgoncalves You can see the issue on the left: `Cannot find module 'is-reachable'`.  @MPierre9 recently landed a change in https://github.com/mozilla/thimble.mozilla.org/pull/2514 that adds a new dependency, and you're missing it locally.

Try doing `npm install` again, and then it should be fine.

**Comment by jmrodriguesgoncalves** [comment]
@humphd, tried doing this, still no success. I also tried cloning the repository into a brand new local folder and doing everything from scratch to make sure I am not missing any of Thimble or Brackets' files , and I still get the exact same same error from above. Here's the log as well, which I didn't include last time:

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle thimble.mozilla.org@2.0.0~prestart: thimble.mozilla.org@2.0.0
6 verbose lifecycle thimble.mozilla.org@2.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle thimble.mozilla.org@2.0.0~prestart: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Joao\desktop\SchoolWork\Year5\Semester1\DPS909\p1\thimble.mozilla.org\node_modules\.bin;C:\Users\Joao\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Joao\bin;C:\Program Files\Git\cmd;C:\app\Joao\product\11.2.0\client_1\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Rational\common;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Android\Android Studio\gradle\gradle-2.4\bin;C:\Android\sdk\tools;C:\Android\sdk\platform-tools;C:\Android\sdk;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\Skype\Phone;C:\Program Files\Git\cmd;C:\HashiCorp\Vagrant\bin;C:\Program Files\nodejs;C:\Users\Joao\.cargo\bin;C:\Program Files\Java\jdk1.8.0_25\bin;C:\Users\Joao\AppData\Local\Microsoft\WindowsApps;C:\Users\Joao\AppData\Local\GitHubDesktop\bin;C:\Users\Joao\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
8 verbose lifecycle thimble.mozilla.org@2.0.0~prestart: CWD: C:\Users\Joao\desktop\SchoolWork\Year5\Semester1\DPS909\p1\thimble.mozilla.org
9 silly lifecycle thimble.mozilla.org@2.0.0~prestart: Args: [ '/d /s /c', 'node scripts/verify-brackets' ]
10 silly lifecycle thimble.mozilla.org@2.0.0~prestart: Returned: code: 1  signal: null
11 info lifecycle thimble.mozilla.org@2.0.0~prestart: Failed to exec prestart script
12 verbose stack Error: thimble.mozilla.org@2.0.0 prestart: `node scripts/verify-brackets`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:920:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
13 verbose pkgid thimble.mozilla.org@2.0.0
14 verbose cwd C:\Users\Joao\desktop\SchoolWork\Year5\Semester1\DPS909\p1\thimble.mozilla.org
15 error Windows_NT 10.0.15063
16 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
17 error node v6.11.3
18 error npm  v3.10.10
19 error code ELIFECYCLE
20 error thimble.mozilla.org@2.0.0 prestart: `node scripts/verify-brackets`
20 error Exit status 1
21 error Failed at the thimble.mozilla.org@2.0.0 prestart script 'node scripts/verify-brackets'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the thimble.mozilla.org package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     node scripts/verify-brackets
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs thimble.mozilla.org
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls thimble.mozilla.org
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

**Comment by gideonthomas** [comment]
@jmrodriguesgoncalves, I filed https://github.com/mozilla/thimble.mozilla.org/issues/2520 since that is a bug that needs to be fixed, sorry about that!

For the time-being, you can run `npm install is-reachable` and that will fix this for you.

**Comment by jmrodriguesgoncalves** [comment]
@gideonthomas, that did it many thanks for the help! I am now able to get to the code editor:

![q3](https://user-images.githubusercontent.com/14240261/31246310-fb0b3ea2-a9da-11e7-99a0-ba70ed13554f.JPG)

However, to reproduce this bug I am required to be signed in. When I try to go to the "Sign In" page, webmaker doesn't quite seem to be able to load:

![q4](https://user-images.githubusercontent.com/14240261/31246320-04213e9c-a9db-11e7-8775-9f798e5dfcc9.JPG)

Could my services not be setup correctly or am I missing a step here?

**Comment by humphd** [comment]
The other students that have faced this reported that their Vagrant VM wasn't fully setup.  They destroyed and recreated it, and it worked.  You should hop into the Thimble chat on Mattermost and talk with people if you can't get it.

**Comment by jmrodriguesgoncalves** [comment]
@humphd yeah I did suspect something along those lines was happening here. Thanks, going to head on over there and ask around about this.

**Comment by jmrodriguesgoncalves** [comment]
@gideonthomas since I got the test environment running, I have been trying to read and understand the code in order to tackle this issue. However as expected, the sheer amount of code is proving to be pretty large.

A couple of comments ago, you mentioned that "To fix this issue, I believe you need to add a function to Publisher.prototype". Now, from what I understand, in order to fix this bug I would need to add functionality to the Cancel button, in order to save the description in a similar fashion to how the Project Title is saved when one clicks on the save button after editing it. I am trying to find out what each function in publisher.js does, and when exactly the event of saving the project name exactly happens. Is this a part of Publisher.prototype.init? 

If you have any further guidance it would be much appreciated!

**Comment by pradeepgangwar** [comment]
@jmrodriguesgoncalves are you still working on the issue? Else I can try. :)

**Comment by KancerEzeroglu** [comment]
Hi @flukeout, if anyone else did not work on this issue I want to take it?
