### ISSUE TITLE
Feature request: Add a "My Projects" link on the homepage for signed in users.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2533]
From an email: 

> I’m a 7th grade student who is learning HTML, and I don’t like what happens when I log into Thimble. I have to go to the top right, click on it, and then click on “My Projects" to see them. I would like it if you made a link to “My Projects” on the main page, so I could easily go to them. And if I weren’t logged in, it would redirect me to the login page, and when I logged in, it would go to my projects. That would be really nice. Here’s an example of how I would want it, in one of these spaces surrounded by black: 

It came with a mockup...

![image](https://user-images.githubusercontent.com/25212/31792877-591d9024-b4d2-11e7-91a2-dcf4865ccf2e.png)

**Comment by jessecalton** [comment]
I can work on this!

**Comment by brianhall** [comment]
Hey there! I'd like to take this on as part of Hacktoberfest. 😄

**Comment by humphd** [comment]
Go for it @brianhall.  Let us know if we can help.

**Comment by brianhall** [comment]
Thanks a bunch! I'm _so close_ to having my local environment up and running, but need a little nudge in the right direction. I've got brackets running locally, and vagrant completes to the point where I can spin up thimble and see the start page at `http://localhost:3500`.

However, when I click on "Create an Account" I get sent to `http://localhost:1234/signup`, but in the console see the following:

```
Loading failed for the <script> with source “http://localhost:1234/assets/app.bundle.js”.
```

When I ssh into the vagrant machine and look at the logs of `id`, `login`, and `publish` they're all up and running, so I'm guessing one of the steps in the asset bundling process failed. [Here is the log output](https://gist.github.com/brianhall/da4df3832fd6275357d73b021d554af8) from doing a `vagrant up` after a fresh destroy. Please let me know if anything familiar jumps out at you. Happy to help debug further, and thanks in advance for your assistance!

**Comment by humphd** [comment]
It sure looks like it's not happy doing the transpile step:

```
==> default: [1m[31mERROR in ./test/manual.tests.jsx
==> default: Module build failed: ReferenceError: [BABEL] /vagrant/services/id.webmaker.org/node_modules/jsx-loader/index.js!/vagrant/services/id.webmaker.org/test/manual.tests.jsx: Unknown option: /vagrant/package.json.presets
==> default:     at Logger.error (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
==> default:     at OptionManager.mergeOptions (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
==> default:     at OptionManager.addConfig (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
==> default:     at OptionManager.findConfigs (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:171:32)
==> default:     at OptionManager.init (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
==> default:     at File.initOptions (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:147:75)
==> default:     at new File (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:137:22)
==> default:     at Pipeline.transform (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
==> default:     at transpile (/vagrant/services/id.webmaker.org/node_modules/babel-loader/index.js:54:24)
==> default:     at Object.module.exports (/vagrant/services/id.webmaker.org/node_modules/babel-loader/index.js:43:24)[39m[22m
==> default: 
==> default: [1m[31mERROR in ./test/browser.tests.jsx
==> default: Module build failed: ReferenceError: [BABEL] /vagrant/services/id.webmaker.org/node_modules/jsx-loader/index.js!/vagrant/services/id.webmaker.org/test/browser.tests.jsx: Unknown option: /vagrant/package.json.presets
==> default:     at Logger.error (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
==> default:     at OptionManager.mergeOptions (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
==> default:     at OptionManager.addConfig (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
==> default:     at OptionManager.findConfigs (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:171:32)
==> default:     at OptionManager.init (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
==> default:     at File.initOptions (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:147:75)
==> default:     at new File (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:137:22)
==> default:     at Pipeline.transform (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
==> default:     at transpile (/vagrant/services/id.webmaker.org/node_modules/babel-loader/index.js:54:24)
==> default:     at Object.module.exports (/vagrant/services/id.webmaker.org/node_modules/babel-loader/index.js:43:24)[39m[22m
==> default: 
==> default: [1m[31mERROR in ./templates/index.jsx
==> default: Module build failed: ReferenceError: [BABEL] /vagrant/services/id.webmaker.org/node_modules/jsx-loader/index.js!/vagrant/services/id.webmaker.org/templates/index.jsx: Unknown option: /vagrant/package.json.presets
==> default:     at Logger.error (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
==> default:     at OptionManager.mergeOptions (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
==> default:     at OptionManager.addConfig (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
==> default:     at OptionManager.findConfigs (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:171:32)
==> default:     at OptionManager.init (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
==> default:     at File.initOptions (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:147:75)
==> default:     at new File (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:137:22)
==> default:     at Pipeline.transform (/vagrant/services/id.webmaker.org/node_modules/babel-loader/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
==> default:     at transpile (/vagrant/services/id.webmaker.org/node_modules/babel-loader/index.js:54:24)
==> default: at Object.module.exports (/vagrant/services/id.webmaker.org/node_modules/babel-loader/index.js:43:24)[39m[22m
```

@gideonthomas, @cadecairos can either of you offer a suggestion to @brianhall on this?  I'm not sure what this is.

@brianhall a bunch of our devs are traveling this week for a conference, so apologies in advance for slow response times.  Also, you may find you get faster answers on https://chat.mozillafoundation.org/mozilla/channels/thimble.

**Comment by cadecairos** [comment]
It looks like the Vagrant box is installing Node 4.8.x

I'm running id on Node 6.10.x (without Vagrant) and id doesn't give me any issues, but maybe something about 4.8.x is breaking babel/webpack?

**Comment by brianhall** [comment]
Cool, I've bumped the version to 6.x and will destroy/recreate the VM and report back. Thanks!

**Comment by brianhall** [comment]
Ok, I made some progress. It turns out that the issue wasn't Node (bumping to Node 6.x didn't seem to change the outcome), but rather an older `babel-loader` dependency in `id.webmaker.org`. Bumping this from `5.0.0` to `6.0.0` eliminates the previous errors. I'll submit a PR shortly to fix, and continue on. Thanks for your help debugging!

**Comment by brianhall** [comment]
@gideonthomas @humphd @cadecairos Ready for review! Thanks again for your assistance.

**Comment by humphd** [comment]
@brianhall this is great, I've flagged some reviewers for you.  NOTE: a bunch of these guys are away this week, so apologies for the turn-around on these PRs.  Really appreciate you jumping in and fixing things here.  Thanks a lot.
