### ISSUE TITLE
TypeError: The "digest" argument is required and must not be undefined ...

### ISSUE THREAD

**Issue by justineuro** [mozilla/thimble.mozilla.org#2559]
In a local offline install of Thimble, while trying to "Sign up" for a new Thimble account through my local install of id.webmaker.org, after filling-up the necessary fields (username, mail, password) and clicking the "SIGN UP" button, I got stuck on the same page and  got the following message in the console where I `npm start`-ed in my id.webmaker.org folder:

>Debug: internal, implementation, error 
>   TypeError: The "digest" argument is required and must not be undefined
>    at pbkdf2 (crypto.js:30:1805)
>    at Object.exports.pbkdf2 (crypto.js:30:1361)
>    at generateKey (/home/juro/Public/id.webmaker.org/node_modules/hapi/node_modules/iron/lib/index.js:123:16)
 >   at generateSalt (/home/juro/Public/id.webmaker.org/node_modules/hapi/node_modules/iron/lib/index.js:118:16)
 >   at generate (/home/juro/Public/id.webmaker.org/node_modules/hapi/node_modules/iron/lib/index.js:104:20)
>    at Object.exports.generateKey (/home/juro/Public/id.webmaker.org/node_modules/hapi/node_modules/iron/lib/index.js:159:5)
>    at Object.exports.encrypt (/home/juro/Public/id.webmaker.org/node_modules/hapi/node_modules/iron/lib/index.js:168:13)
>    at Object.exports.seal (/home/juro/Public/id.webmaker.org/node_modules/hapi/node_modules/iron/lib/index.js:277:13)
>    at Object.internals.encode (/home/juro/Public/id.webmaker.org/node_modules/hapi/node_modules/statehood/lib/index.js:468:14)
>    at Object.exports.prepareValue (/home/juro/Public/id.webmaker.org/node_modules/hapi/node_modules/statehood/lib/index.js:433:15) "digest" argument is required and must not be undefined

Thanks in advance as to any info as to what's causing the error.

**Comment by gideonthomas** [comment]
Hi @justineuro are you running Thimble without vagrant? If so, you would need to use a node version < 7 for running id.webmaker.org since node 7.x.x introduced a breaking change.
